export const API_BASE = "http://127.0.0.1:8123/api";

// 桌宠流式输出协议：用于从“进度日志 + 最终输出”混合文本中提取最终结果
export const PET_STREAM_RESULT_TAG = "【结果】";
export const PET_PLAN_HIDE_DELAY_MS = 2200;
export const PET_INPUT_HISTORY_LIMIT = 50;
// 前端轮询默认频率（用于世界页/概览/桌宠状态刷新）
export const UI_POLL_INTERVAL_MS = 1200;

export const UI_TEXT = {
  APP_TITLE: "智能体",
  ENTRY_TITLE: "入口",
  PANEL_TITLE: "面板",
  PET_TITLE: "桌宠",
  APP_VERSION_LABEL: "v0.1.0 Alpha",
  ENTRY_DESC: "这里是前端主入口，你可以进入主面板查看当前实现情况。",
  ENTRY_OPEN_PANEL: "进入主面板",
  ENTRY_OPEN_PET: "查看桌宠页面",
  ENTRY_NOTE: "提示：托盘入口仍可随时打开主面板。",
  TAB_DASHBOARD: "概览",
  TAB_TASKS: "任务",
  TAB_MEMORY: "记忆",
  TAB_SKILLS: "技能",
  TAB_GRAPH: "图谱",
  TAB_EVAL: "评估",
  TAB_SYSTEM: "系统",
  TAB_SETTINGS: "设置",
  PAGE_WORLD: "世界",
  PAGE_STATE: "状态",
  PANEL_HOME_TITLE: "主页面入口",
  PANEL_HOME_DESC: "点击下方按钮进入主页面（世界/状态）。",
  PANEL_HOME_ENTER: "进入主页面",
  WINDOW_MINIMIZE_TITLE: "最小化",
  WINDOW_MAXIMIZE_TITLE: "最大化 / 还原",
  WINDOW_CLOSE_TITLE: "关闭（隐藏）",
  STATUS_BACKEND_LABEL: "后端：",
  STATUS_TASK_COUNT_LABEL: "任务数：",
  STATUS_TASK_CURRENT_LABEL: "当前任务：",
  TASKS_DESC: "任务队列 / 步骤 / 输出",
  MEMORY_DESC: "记忆条目 / 检索 / 注入",
  SKILLS_DESC: "技能卡 / 复盘 / 复用记录",
  GRAPH_DESC: "实体 / 关系 / 证据",
  GRAPH_ZOOM_IN_TITLE: "放大",
  GRAPH_ZOOM_OUT_TITLE: "缩小",
  GRAPH_ZOOM_RESET_TITLE: "居中",
  GRAPH_NODE_UPDATE_TITLE: "更新节点",
  GRAPH_EDGE_UPDATE_TITLE: "更新关系",
  EVAL_DESC: "展示 Agent 自动复盘的评估记录：问题清单 / 改进建议 / 技能沉淀。",
  EVAL_USER_SECTION_TITLE: "用户期望与评估",
  EVAL_EXPECTATION_TITLE: "提交期望",
  EVAL_SUBMIT_TITLE: "提交评估",
  EVAL_FETCH_TITLE: "查询评估",
  AGENT_EVAL_TITLE: "Agent 评估（自动复盘）",
  AGENT_EVAL_DESC: "对某次 run 的执行过程做复盘：问题清单 / 改进建议 / 0..N 个技能卡沉淀。",
  AGENT_EVAL_RUN_ID_PLACEHOLDER: "run_id（例如 12，可在桌宠 /do 后显示）",
  AGENT_EVAL_NOTE_PLACEHOLDER: "补充说明（可选）",
  AGENT_EVAL_START_BUTTON: "开始评估",
  AGENT_EVAL_OUTPUT_LABEL: "评估输出：",
  AGENT_EVAL_PLAN_LABEL: "评估计划：",
  AGENT_REVIEW_LIST_LABEL: "评估记录：",
  AGENT_REVIEW_DETAIL_LABEL: "评估详情：",
  AGENT_REVIEW_SKILLS_LABEL: "技能沉淀：",
  SYSTEM_DESC: "统一检索 / 工具 / 记录 / 配置 / 权限（系统运维与调试入口）",
  SYSTEM_SUBTAB_SEARCH: "检索",
  SYSTEM_SUBTAB_TOOLS: "工具",
  SYSTEM_SUBTAB_RECORDS: "记录",
  SYSTEM_SUBTAB_CONFIG: "配置",
  SYSTEM_SUBTAB_PERMISSIONS: "权限",
  SYSTEM_SEARCH_TITLE: "统一检索",
  SYSTEM_TOOLS_TITLE: "工具管理",
  SYSTEM_LLM_RECORDS_TITLE: "LLM 记录",
  SYSTEM_TOOL_RECORDS_TITLE: "工具调用记录",
  SETTINGS_DESC: "配置 LLM 连接信息（API Key / Base URL / Model），并影响桌宠对话与图谱抽取等后端能力。",
  SETTINGS_LLM_TITLE: "LLM 配置",
  LLM_CONFIG_PROVIDER_LABEL: "Provider：",
  LLM_CONFIG_PROVIDER_PLACEHOLDER: "例如 openai（可空；默认 openai）",
  LLM_CONFIG_API_KEY_LABEL: "API Key：",
  LLM_CONFIG_API_KEY_PLACEHOLDER: "输入 API Key（留空不修改）",
  LLM_CONFIG_API_KEY_PLACEHOLDER_SET: "已配置（输入新值可覆盖；勾选“清空”可移除）",
  LLM_CONFIG_BASE_URL_LABEL: "Base URL：",
  LLM_CONFIG_BASE_URL_PLACEHOLDER: "例如 https://api.openai.com/v1（可空）",
  LLM_CONFIG_MODEL_LABEL: "默认模型：",
  LLM_CONFIG_MODEL_PLACEHOLDER: "例如 gpt-4o-mini（可空）",
  LLM_CONFIG_CLEAR_LABEL: "清空",
  LLM_CONFIG_LOAD_LABEL: "读取LLM配置",
  LLM_CONFIG_SAVE_LABEL: "保存LLM配置",
  LLM_CONFIG_STATUS_OK: "已更新",
  LLM_CONFIG_STATUS_FAIL: "更新失败",
  LLM_CONFIG_STATUS_LOADED: "已加载",
  SYSTEM_CONFIG_TITLE: "配置",
  SYSTEM_PERMISSIONS_TITLE: "权限",
  SYSTEM_ACTIONS_TITLE: "动作开关",
  SYSTEM_TOOLS_TOGGLE_TITLE: "工具开关",
  PERMISSIONS_TOGGLE_LABEL: "启用",
  CONFIG_TRAY_LABEL: "托盘启用",
  CONFIG_PET_LABEL: "桌宠启用",
  CONFIG_PANEL_LABEL: "面板启用",
  PERMISSIONS_PATHS_LABEL: "允许路径",
  PERMISSIONS_OPS_LABEL: "允许操作",
  PERMISSIONS_READ_LABEL: "read",
  PERMISSIONS_WRITE_LABEL: "write",
  PERMISSIONS_EXEC_LABEL: "execute",
  CONFIG_LOAD_LABEL: "读取配置",
  CONFIG_SAVE_LABEL: "更新配置",
  PERMISSIONS_LOAD_LABEL: "读取权限",
  PERMISSIONS_SAVE_LABEL: "更新权限",
  SEARCH_DETAIL_LABEL: "检索详情：",
  SEARCH_INJECTION_LABEL: "注入片段：",
  SEARCH_TYPE_MEMORY_LABEL: "memory",
  SEARCH_TYPE_SKILLS_LABEL: "skills",
  SEARCH_TYPE_GRAPH_LABEL: "graph",
  TASK_LATEST_LABEL: "最新任务：",
  TASK_LIST_LABEL: "任务列表：",
  TASK_BACKEND_LABEL: "后端状态：",
  MEMORY_LATEST_LABEL: "最新记忆：",
  MEMORY_LIST_LABEL: "列表：",
  MEMORY_COUNT_LABEL: "条目数：",
  SKILLS_LATEST_LABEL: "最新技能：",
  SKILLS_LIST_LABEL: "列表：",
  SKILLS_COUNT_LABEL: "技能数：",
  GRAPH_NODES_LIST_LABEL: "节点列表：",
  GRAPH_EDGES_LIST_LABEL: "关系列表：",
  GRAPH_NODES_COUNT_LABEL: "节点：",
  GRAPH_EDGES_COUNT_LABEL: "关系：",
  EVAL_DETAIL_LABEL: "评估详情：",
  EVAL_STATUS_LABEL: "状态：",
  EVAL_SCORE_LABEL: "评分：",
  SEARCH_RESULT_LABEL: "检索结果：",
  TOOL_LIST_LABEL: "工具列表：",
  LLM_RECORD_LIST_LABEL: "LLM记录：",
  TOOL_RECORD_LIST_LABEL: "工具记录：",
  CONFIG_STATUS_LABEL: "配置状态：",
  PERMISSIONS_STATUS_LABEL: "权限状态：",
  DASHBOARD_QUICK_ACTIONS: "快捷操作",
  DASHBOARD_AGENT_BRAIN_TITLE: "Agent 大脑",
  DASHBOARD_AGENT_BRAIN_PLACEHOLDER: "正在读取当前任务…",
  DASHBOARD_AGENT_PLAN_TITLE: "计划",
  DASHBOARD_AGENT_THOUGHTS_TITLE: "想法 / 观测",
  DASHBOARD_ACTIVITY_TITLE: "最近动态",
  DASHBOARD_REFRESH_STATUS: "刷新状态",
  TASK_NEW_LABEL: "新建任务",
  PET_BUBBLE: "",
  PET_CHAT_PLACEHOLDER: "和雷姆说点什么…（普通对话直接发；任务用 /do；Enter 发送）",
  PET_CHAT_SENDING: "雷姆思考中…",
  PET_TASK_FEEDBACK_PROMPT: "你对本次任务的执行满意吗？",
  PET_SYSTEM_PROMPT: "你是桌宠雷姆（Re:Zero 角色形象），用简洁、温柔、略带俏皮的中文回答。回答尽量分句输出，避免一大段。若信息不足就先问一个澄清问题。",
  BUTTON_SEND: "发送",
  BUTTON_SUBMIT: "提交",
  BUTTON_WRITE: "写入",
  BUTTON_SEARCH: "检索",
  BUTTON_REFRESH: "刷新",
  BUTTON_UPDATE: "更新",
  BUTTON_UPDATE_TASK: "更新任务",
  BUTTON_ADD_NODE: "新增节点",
  BUTTON_ADD_EDGE: "新增关系",
  BUTTON_UPDATE_NODE: "更新节点",
  BUTTON_UPDATE_EDGE: "更新关系",
  BUTTON_SUBMIT_EXPECTATION: "提交期望",
  BUTTON_SUBMIT_EVAL: "提交评估",
  BUTTON_FETCH_EVAL: "获取评估",
  BUTTON_REGISTER_TOOL: "注册工具",
  BUTTON_WRITE_LLM: "写入LLM记录",
  BUTTON_WRITE_TOOL_RECORD: "写入工具记录",
  BUTTON_CLOSE: "关闭",
  BUTTON_CANCEL: "取消",
  BUTTON_YES: "是",
  BUTTON_NO: "否",
  BUTTON_EXPAND: "展开",
  BUTTON_COLLAPSE: "收起",
  TASK_CREATE_BTN: "创建任务",
  TASK_TITLE_PLACEHOLDER: "输入任务标题",
  TASK_EXPECTATION_PLACEHOLDER: "期望ID(可选)",
  TASK_UPDATE_ID_PLACEHOLDER: "任务ID",
  TASK_UPDATE_TITLE_PLACEHOLDER: "新标题(可选)",
  MEMORY_CONTENT_PLACEHOLDER: "输入记忆内容",
  MEMORY_SEARCH_PLACEHOLDER: "记忆检索关键词",
  MEMORY_UPDATE_ID_PLACEHOLDER: "记忆ID",
  MEMORY_UPDATE_CONTENT_PLACEHOLDER: "新内容",
  MEMORY_LOADING: "记忆加载中...",
  MEMORY_EMPTY: "暂无记忆",
  MEMORY_SEARCH_EMPTY: "未找到匹配记忆",
  MEMORY_DELETE_CONFIRM: "确定删除该记忆？",
  SKILLS_NAME_PLACEHOLDER: "输入技能名称",
  SKILLS_SEARCH_PLACEHOLDER: "技能检索关键词",
  SKILLS_UPDATE_ID_PLACEHOLDER: "技能ID",
  SKILLS_UPDATE_NAME_PLACEHOLDER: "新名称",
  SKILLS_FULL_NAME_PLACEHOLDER: "例如 text_summarizer",
  SKILLS_FULL_DESC_PLACEHOLDER: "该技能的用途说明",
  SKILLS_FULL_SCOPE_PLACEHOLDER: "例如 text_processing",
  SKILLS_FULL_INPUTS_PLACEHOLDER: "text, length",
  SKILLS_FULL_OUTPUTS_PLACEHOLDER: "summary",
  SKILLS_FULL_STEPS_PLACEHOLDER: "1. 接收文本\n2. 处理文本\n3. 输出结果",
  GRAPH_NODE_LABEL_PLACEHOLDER: "实体名称",
  GRAPH_EDGE_SOURCE_PLACEHOLDER: "起点ID",
  GRAPH_EDGE_TARGET_PLACEHOLDER: "终点ID",
  GRAPH_EDGE_RELATION_PLACEHOLDER: "关系类型",
  GRAPH_NODE_UPDATE_ID_PLACEHOLDER: "节点ID",
  GRAPH_NODE_UPDATE_LABEL_PLACEHOLDER: "新节点名",
  GRAPH_EDGE_UPDATE_ID_PLACEHOLDER: "关系ID",
  GRAPH_EDGE_UPDATE_RELATION_PLACEHOLDER: "新关系",
  EXPECTATION_GOAL_PLACEHOLDER: "期望描述",
  EXPECTATION_CRITERIA_PLACEHOLDER: "验收标准(逗号分隔)",
  EVAL_SCORE_PLACEHOLDER: "评分(0-1)",
  EVAL_NOTES_PLACEHOLDER: "说明(可选)",
  EVAL_TASK_ID_PLACEHOLDER: "任务ID(可选)",
  EVAL_EXPECTATION_ID_PLACEHOLDER: "期望ID(可选)",
  EVAL_FETCH_ID_PLACEHOLDER: "评估ID",
  SEARCH_QUERY_PLACEHOLDER: "统一检索关键词",
  SEARCH_LIMIT_PLACEHOLDER: "limit(可选)",
  TOOL_NAME_PLACEHOLDER: "工具名称",
  TOOL_DESC_PLACEHOLDER: "工具描述",
  TOOL_VERSION_PLACEHOLDER: "版本(如0.1.0)",
  LLM_PROMPT_PLACEHOLDER: "LLM Prompt",
  LLM_RESPONSE_PLACEHOLDER: "LLM Response",
  LLM_TASK_ID_PLACEHOLDER: "任务ID(可选)",
  TOOL_RECORD_TOOL_PLACEHOLDER: "工具ID",
  TOOL_RECORD_TASK_PLACEHOLDER: "任务ID(可选)",
  TOOL_RECORD_SKILL_PLACEHOLDER: "技能ID(可选)",
  TOOL_RECORD_INPUT_PLACEHOLDER: "输入",
  TOOL_RECORD_OUTPUT_PLACEHOLDER: "输出",
  PERMISSIONS_PATHS_PLACEHOLDER: "路径(逗号分隔)",
  TASKS_RECENT_LABEL: "近期任务",
  TASK_FILTER_DATE_LABEL: "日期",
  TASK_FILTER_DAYS_LABEL: "天数",
  TASK_FILTER_DAYS_PLACEHOLDER: "1-31",
  TASK_FILTER_CLEAR_BTN: "清除",
  WORLD_TASK_PLAN_TITLE: "任务plan-list栏",
  WORLD_EVAL_PLAN_TITLE: "评估plan-list栏",
  WORLD_RESULT_TITLE: "结果显示栏",
  WORLD_THOUGHTS_TITLE: "思考、规划过程显示栏",
  WORLD_PET_TITLE: "桌宠形象栏",
  WORLD_UPLOAD_BTN: "文件上传",
  WORLD_INPUT_PLACEHOLDER: "输入框",
  TASK_DRAWER_TITLE_PLACEHOLDER: "任务详情",
  TASK_DRAWER_ACTIONS_TITLE: "状态与操作",
  TASK_DRAWER_STEPS_TITLE: "执行步骤",
  TASK_DRAWER_TIMELINE_TITLE: "时间线",
  MEMORY_DRAWER_TITLE_PLACEHOLDER: "记忆详情",
  MEMORY_DETAIL_LOADING: "记忆详情加载中...",
  MEMORY_DETAIL_LOAD_FAIL: "记忆详情加载失败",
  TASK_STATUS_LOADING: "加载中...",
  TASK_STEPS_LOADING: "步骤加载中...",
  TASK_TIMELINE_LOADING: "时间线加载中...",
  TASK_STEPS_EMPTY: "暂无步骤",
  TASK_TIMELINE_EMPTY: "暂无时间线",
  TASK_DETAIL_LOAD_FAIL: "详情加载失败",
  TASK_STATUS_UPDATE_FAIL: "任务状态更新失败",
  TASK_EXECUTE_FAIL: "任务执行失败",
  TASKS_LOADING: "任务加载中...",
  TASKS_EMPTY: "暂无任务，请先创建",
  TASKS_EMPTY_FILTER: "该日期范围暂无任务",
  TASK_TITLE_TEMPLATE: "任务 #{id}",
  TASK_TITLE_WITH_NAME_TEMPLATE: "任务 #{id}: {title}",
  TASK_CREATED_RECENT: "刚刚",
  TASK_EVENT_DEFAULT: "事件",
  SKILLS_CREATE_BTN: "新建技能",
  SKILLS_CREATE_TITLE: "创建新技能",
  SKILLS_CREATE_SUBMIT: "创建技能",
  SKILLS_DRAWER_TITLE_PLACEHOLDER: "技能详情",
  SKILLS_IO_SPEC_LABEL: "输入输出",
  SKILLS_INPUTS_LABEL: "输入",
  SKILLS_OUTPUTS_LABEL: "输出",
  SKILLS_STEPS_LABEL: "步骤",
  SKILLS_DELETE_BTN: "删除技能",
  SKILLS_FORM_NAME_LABEL: "技能名称 *",
  SKILLS_FORM_DESC_LABEL: "描述",
  SKILLS_FORM_SCOPE_LABEL: "范围",
  SKILLS_FORM_VERSION_LABEL: "版本",
  SKILLS_FORM_INPUTS_LABEL: "输入（逗号分隔）",
  SKILLS_FORM_OUTPUTS_LABEL: "输出（逗号分隔）",
  SKILLS_FORM_STEPS_LABEL: "步骤（每行一个）",
  SKILLS_LOADING: "技能加载中...",
  SKILLS_EMPTY: "暂无技能",
  SKILLS_SEARCH_EMPTY: "未找到匹配技能",
  SKILLS_SEARCHING: "检索中...",
  SKILLS_NO_DESC: "暂无描述",
  SKILLS_NO_STEPS: "暂无步骤",
  SKILLS_SCOPE_DEFAULT: "通用",
  SKILLS_VERSION_DEFAULT: "1.0",
  SKILLS_DELETE_CONFIRM: "确定删除该技能？",
  SKILLS_SEARCH_FAIL: "检索失败",
  SKILLS_DETAIL_LOADING: "加载中...",
  SKILLS_DETAIL_LOAD_FAIL: "技能加载失败",
  CONFIG_STATUS_OK: "已加载",
  CONFIG_STATUS_FAIL: "加载失败",
  PERMISSIONS_STATUS_OK: "已加载",
  PERMISSIONS_STATUS_FAIL: "加载失败",
  LOADING: "检测中...",
  LOAD_LIST: "加载中...",
  LOAD_FAIL: "加载失败",
  SEARCH_FAIL: "检索失败",
  WRITE_FAIL: "写入失败",
  SUBMIT_FAIL: "提交失败",
  UPDATE_FAIL: "更新失败",
  UNAVAILABLE: "不可用",
  NONE: "无",
  NO_DATA: "暂无数据",
  SEARCHING: "检索中...",
  TOOL_CREATE_FAIL: "工具创建失败",
  LLM_RECORD_FAIL: "LLM记录写入失败",
  TOOL_RECORD_FAIL: "工具记录写入失败",
  EXPECTATION_FAIL: "期望提交失败",
  EVAL_SUBMIT_FAIL: "评估提交失败",
  EVAL_FETCH_FAIL: "评估读取失败",
  EXPECTATION_SUCCESS_TEMPLATE: "期望已创建 #{id}",
  EVAL_SUBMIT_SUCCESS_TEMPLATE: "评估已提交 #{id}",
  EVAL_FETCH_TEMPLATE: "#{id} {status} {score}",
  VALIDATION_REQUIRED: "请填写必填项",
  VALIDATION_NUMBER: "请输入有效数字",
  VALIDATION_RANGE: "数值超出范围",
  VALIDATION_SELECT: "请选择有效选项",
  VALIDATION_TASK_UPDATE_REQUIRED: "请输入新标题或选择状态",
  BACKEND_STATUS: "ok",
  TASK_DONE_LABEL: "完成",
  TASK_CANCEL_LABEL: "取消",
  TASK_RESUME_LABEL: "继续执行",
  BUTTON_COPY: "复制",
  BUTTON_DELETE: "删除",
  COPY_OK: "已复制到剪贴板",
  COPY_FAIL: "复制失败（请手动选择文本复制）",
  DASH: "-",
  SEARCH_SUMMARY_TEMPLATE: "memory:{memory} skills:{skills} graph:{graph}",
  LIST_ITEM_TASK: "#{id} {title} [{status}]",
  LIST_ITEM_MEMORY: "#{id} {content}",
  LIST_ITEM_SKILL: "#{id} {name}",
  LIST_ITEM_GRAPH_NODE: "#{id} {label}",
  LIST_ITEM_GRAPH_EDGE: "#{id} {source}→{target} ({relation})",
  LIST_ITEM_TOOL: "#{id} {name} ({version})",
  LIST_ITEM_LLM: "#{id} task:{task} {prompt}",
  LIST_ITEM_TOOL_RECORD: "#{id} tool:{tool} task:{task} reuse:{reuse}"
  ,
  LIST_ITEM_SEARCH_RESULT: "[{type}] {text}",
  LIST_ITEM_INJECTION: "[{type}] w:{weight} {snippet}"
};

export const SELECT_PLACEHOLDERS = {
  TASK_STATUS: "状态(可选)",
  EVAL_STATUS: "评估状态"
};

export const TASK_STATUS_OPTIONS = ["queued", "running", "waiting", "done", "cancelled", "failed", "stopped"];

export const EVAL_STATUS_OPTIONS = ["pass", "fail", "unknown"];

export const TASK_STATUS = {
  QUEUED: "queued",
  RUNNING: "running",
  WAITING: "waiting",
  DONE: "done",
  CANCELLED: "cancelled",
  FAILED: "failed",
  STOPPED: "stopped"
};

export const EVAL_STATUS_DEFAULT = "unknown";

export const REUSE_OPTIONS = [
  { value: "", label: "是否复用" },
  { value: "true", label: "true" },
  { value: "false", label: "false" }
];

export const UI_THEME = {
  FONT_PRIMARY: "\"PingFang SC\", \"Microsoft YaHei\", \"Noto Sans SC\", \"Source Han Sans SC\", sans-serif",
  FONT_DISPLAY: "\"Songti SC\", \"STSong\", \"Noto Serif SC\", \"Source Han Serif SC\", serif",
  COLOR_INK: "#1f1c17",
  COLOR_PAPER: "#fff8ee",
  COLOR_PAPER_ALT: "#f3e7d3",
  COLOR_BG_START: "#f4efe6",
  COLOR_BG_END: "#e7ddcf",
  COLOR_BORDER: "#2b241c",
  COLOR_ALERT: "#ffe3e1",
  COLOR_PET: "#f5e4c3",
  COLOR_FACE: "#1a120c",
  COLOR_BUBBLE: "#fff6d9",
  COLOR_PAPER_FAINT: "#fffdf7",
  COLOR_BUBBLE_BORDER: "#1a120c",
  COLOR_ACCENT: "#d97757",
  COLOR_ACCENT_SOFT: "#f5cda7",
  COLOR_ACCENT_DEEP: "#8c3f2a",
  COLOR_MUTED: "#6f5d4c",
  COLOR_SHADOW: "rgba(28, 20, 12, 0.12)"
};

export const BOOL_OPTIONS = [
  { value: "true", label: "true" },
  { value: "false", label: "false" }
];

export const INPUT_ATTRS = {
  TASK_EXPECTATION_ID: { min: 1 },
  TASK_FILTER_DAYS: { min: 1, max: 31, step: 1 },
  TASK_UPDATE_ID: { min: 1 },
  MEMORY_UPDATE_ID: { min: 1 },
  SKILLS_UPDATE_ID: { min: 1 },
  SKILLS_FULL_VERSION: { value: "1.0.0" },
  GRAPH_NODE_ID: { min: 1 },
  GRAPH_EDGE_SOURCE: { min: 1 },
  GRAPH_EDGE_TARGET: { min: 1 },
  GRAPH_EDGE_ID: { min: 1 },
  EVAL_SCORE: { min: 0, max: 1, step: 0.1 },
  EVAL_TASK_ID: { min: 1 },
  EVAL_EXPECTATION_ID: { min: 1 },
  EVAL_FETCH_ID: { min: 1 },
  SEARCH_LIMIT: { min: 1 },
  TOOL_RECORD_TOOL: { min: 1 },
  TOOL_RECORD_TASK: { min: 1 },
  TOOL_RECORD_SKILL: { min: 1 },
  LLM_TASK_ID: { min: 1 },
  // 预留：如后续新增输入约束，请集中写在此处，避免散落在业务逻辑里
};
